### ISSUE TITLE
Integration tab crash

### ISSUE THREAD

**Issue by joseivanlopez** [cockpit-project/cockpit-podman#1109]
Cockpit version: 276.1-1.1
Cockpit-podman version: 53-1.1 
Podman version: 4.2.0-1.2
OS: openSUSE Tumbleweed 20220923

### Problem

In the containers list, each container entry has 4 tabs: Details, Integration, Logs and Console. Everything works as expected except the Integration tab which reports js errors in the browser console and the whole page gets blank. Nevertheless, Integration tab works as expected in the dialog for creating a container. Note that this problem occurs when using *docker.io/opensuse/tumbleweed:latest* image. With other images it seems to work.

### Steps to reproduce

* Pull *docker.io/opensuse/tumbleweed:latest* image.
* Create a container with default values.
* In the container list, select the container and click Integration tab.

### Logs

Nothing is printed to journalctl, so it seems to be a pure UI error.

Web console logs:

~~~
ContainerIntegration.jsx:52 Uncaught TypeError: imageEnv is not iterable
    at renderContainerEnv (ContainerIntegration.jsx:52:29)
    at ContainerIntegration (ContainerIntegration.jsx:100:17)
    at renderWithHooks (react-dom.development.js:14985:1)
    at mountIndeterminateComponent (react-dom.development.js:17811:1)
    at beginWork (react-dom.development.js:19049:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23964:1)
    at performUnitOfWork (react-dom.development.js:22779:1)
react-dom.development.js:20085 The above error occurred in the <ContainerIntegration> component:

    at ContainerIntegration (https://192.168.100.148:9090/cockpit/$f640f64e433ba341a8692a2002b93372678adba4748efcee330b92602f24cdc6/podman/index.js:21357:24)
    at div
    at section
    at TabContentBase (https://192.168.100.148:9090/cockpit/$f640f64e433ba341a8692a2002b93372678adba4748efcee330b92602f24cdc6/podman/index.js:7826:11)
    at Tabs (https://192.168.100.148:9090/cockpit/$f640f64e433ba341a8692a2002b93372678adba4748efcee330b92602f24cdc6/podman/index.js:7929:9)
    at div
    at ListingPanel (https://192.168.100.148:9090/cockpit/$f640f64e433ba341a8692a2002b93372678adba4748efcee330b92602f24cdc6/podman/index.js:19840:5)
    at div
    at ExpandableRowContent (https://192.168.100.148:9090/cockpit/$f640f64e433ba341a8692a2002b93372678adba4748efcee330b92602f24cdc6/podman/index.js:17564:11)
    at td
    at TdBase (https://192.168.100.148:9090/cockpit/$f640f64e433ba341a8692a2002b93372678adba4748efcee330b92602f24cdc6/podman/index.js:18703:11)
    at Td
    at tr
    at TrBase (https://192.168.100.148:9090/cockpit/$f640f64e433ba341a8692a2002b93372678adba4748efcee330b92602f24cdc6/podman/index.js:18997:11)
    at Tr
    at tbody
    at TbodyBase (https://192.168.100.148:9090/cockpit/$f640f64e433ba341a8692a2002b93372678adba4748efcee330b92602f24cdc6/podman/index.js:18654:11)
    at Tbody
    at table
    at TableComposableBase (https://192.168.100.148:9090/cockpit/$f640f64e433ba341a8692a2002b93372678adba4748efcee330b92602f24cdc6/podman/index.js:18573:11)
    at TableComposable
    at ListingTable (https://192.168.100.148:9090/cockpit/$f640f64e433ba341a8692a2002b93372678adba4748efcee330b92602f24cdc6/podman/index.js:20025:27)
    at article
    at Card (https://192.168.100.148:9090/cockpit/$f640f64e433ba341a8692a2002b93372678adba4748efcee330b92602f24cdc6/podman/index.js:583:11)
    at div
    at Flex (https://192.168.100.148:9090/cockpit/$f640f64e433ba341a8692a2002b93372678adba4748efcee330b92602f24cdc6/podman/index.js:13529:11)
    at div
    at CardBody (https://192.168.100.148:9090/cockpit/$f640f64e433ba341a8692a2002b93372678adba4748efcee330b92602f24cdc6/podman/index.js:684:11)
    at article
    at Card (https://192.168.100.148:9090/cockpit/$f640f64e433ba341a8692a2002b93372678adba4748efcee330b92602f24cdc6/podman/index.js:583:11)
    at div
    at Containers (https://192.168.100.148:9090/cockpit/$f640f64e433ba341a8692a2002b93372678adba4748efcee330b92602f24cdc6/podman/index.js:22595:5)
    at div
    at Stack (https://192.168.100.148:9090/cockpit/$f640f64e433ba341a8692a2002b93372678adba4748efcee330b92602f24cdc6/podman/index.js:13696:11)
    at section
    at PageSection (https://192.168.100.148:9090/cockpit/$f640f64e433ba341a8692a2002b93372678adba4748efcee330b92602f24cdc6/podman/index.js:5295:11)
    at main
    at div
    at Page (https://192.168.100.148:9090/cockpit/$f640f64e433ba341a8692a2002b93372678adba4748efcee330b92602f24cdc6/podman/index.js:5098:9)
    at WithDialogs (https://192.168.100.148:9090/cockpit/$f640f64e433ba341a8692a2002b93372678adba4748efcee330b92602f24cdc6/podman/index.js:20356:23)
    at Application (https://192.168.100.148:9090/cockpit/$f640f64e433ba341a8692a2002b93372678adba4748efcee330b92602f24cdc6/podman/index.js:26533:5)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:20085
react-dom.development.js:11340 Uncaught TypeError: imageEnv is not iterable
    at renderContainerEnv (ContainerIntegration.jsx:52:29)
    at ContainerIntegration (ContainerIntegration.jsx:100:17)
    at renderWithHooks (react-dom.development.js:14985:1)
    at mountIndeterminateComponent (react-dom.development.js:17811:1)
    at beginWork (react-dom.development.js:19049:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23964:1)
    at performUnitOfWork (react-dom.development.js:22779:1)
~~~

### Screenshots

![Screenshot from 2022-09-29 09-27-58](https://user-images.githubusercontent.com/1112304/192984674-7b3cee62-5eec-4eae-96a6-8caf65cb4264.png)

Result after clicking on Integration:

![Screenshot from 2022-09-29 09-44-40](https://user-images.githubusercontent.com/1112304/192984907-d81e922e-6f11-425e-abfd-82630f071401.png)

**Comment by joseivanlopez** [comment]
Thanks a lot!
